server:
  port: 8081

spring:
  sql:
    init:
      mode: always
      encoding: UTF-8
  kafka:
    consumer:
      group-id: midas-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      value-type: com.jpmc.midascore.foundation.Transaction
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"

midas:
  kafka:
    topic: forage-midas-topic

  datasource:
    url: jdbc:h2:mem:midasdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true




